
set(RENDER_FILES
        render/app/AppBase.cpp
        render/app/AppBase.h
        render/app/AppGLFW.cpp
        render/app/AppGLFW.h
        render/asset/AssetBase.cpp
        render/asset/AssetBase.h
        render/asset/AssetBufferObjects.cpp
        render/asset/AssetBufferObjects.h
        render/asset/AssetShaders.h
        render/asset/Mesh.cpp
        render/asset/Mesh.h
        render/buffer/Buffer.h
        render/buffer/Buffer.hpp
        render/buffer/BufferObject.cpp
        render/buffer/BufferObject.h
        render/buffer/BufferTraits.hpp
        render/buffer/BufferUtil.h
        render/camera/CameraBase.cpp
        render/camera/CameraBase.h
        render/capture/BufferCapture.cpp
        render/capture/BufferCapture.h
        render/capture/TextureCapture.cpp
        render/capture/TextureCapture.h
        render/gl/Camera.cpp
        render/gl/Camera.h
        render/gl/glew.cpp
        render/gl/glew.h
        render/gl/glxew.h
        render/gl/wglew.h
        render/imgui/imgui.cpp
        render/imgui/imgui_draw.cpp
        render/imgui/imgui_custom.cpp
        render/imgui/imgui_impl_glfw_gl3.cpp
        render/math/mat2.h
        render/math/mat3.h
        render/math/mat4.h
        render/math/math.cpp
        render/math/quat.h
        render/math/util.h
        render/math/vec2.h
        render/math/vec3.h
        render/math/vec4.h
        render/overlay/Overlay.cpp
        render/overlay/Overlay.h
        render/overlay/ScreenOverlay.cpp
        render/overlay/ScreenOverlay.h
        render/render/app.h
        render/render/buffer.h
        render/render/camera.h
        render/render/gl.h
        render/render/math.h
        render/render/overlay.h
        render/render/shader.h
        render/render/texture.h
        render/render/time.h
        render/shader/Shader.cpp
        render/shader/Shader.h
        render/shader/Shader.hpp
        render/shader/ShaderAttributes.cpp
        render/shader/ShaderImage.hpp
        render/shader/ShaderMath.cpp
        render/shader/ShaderProgram.cpp
        render/shader/ShaderProgram.h
        render/shader/ShaderPrograms.cpp
        render/shader/ShaderPrograms.h
        render/shader/ShaderTexture.hpp
        render/shader/ShaderUniforms.cpp
        render/texture/Texture.cpp
        render/texture/Texture.h
        render/texture/Texture1D.h
        render/texture/Texture1D_Array.h
        render/texture/Texture2D.h
        render/texture/Texture2D_Array.h
        render/texture/Texture3D.h
        render/texture/TextureCube.h
        render/texture/TextureT.h
        render/texture/Traits.h
        render/time/Profiler.cpp
        render/time/Profiler.h
        render/time/Timer.cpp
        render/time/Timer.h)